### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by aldakata** [bupt-ai-cz/PGDF#1]
An installation file with the requirements would be handy to install all the dependencies with pip.

I believe that there is a simple command to generate a requirements.txt given an environment.

Thanks!

**Comment by aldakata** [comment]
For instance, the code doesn't run with PyTorch 1.9 because of [this known bug](https://github.com/pytorch/pytorch/issues/44714)

**Comment by buptcwk** [comment]
Thanks for your advice! We will add the requirements.txt file soon!

**Comment by buptcwk** [comment]
[requirements.txt](https://github.com/bupt-ai-cz/PGDF/blob/main/requirements.txt)
