### ISSUE TITLE
details about mini webvision1.0 dataset

### ISSUE THREAD

**Issue by Christophe-Jia** [bupt-ai-cz/PGDF#2]
Thanks for your brilliant work first.
Actually we try to replicate your results, so i was wondering that how many samples does the mini Webvision 1.0 dataset your used in this work contain? Is that 61K? I was so confused because some works state that they also use a subset of the first 50 classes in webvision1.0 which contains more than 100K samples in training set, such as Aum[https://arxiv.org/abs/2001.10528].
Looking forward for your kindly help

**Comment by buptcwk** [comment]
It seems that it contains 65944 samples for training and 2500 samples for testing (if my calculation script is correct), as the same with work "[DivideMix](https://github.com/LiJunnan1992/DivideMix)".

**Comment by Christophe-Jia** [comment]
Thank you!
